### ISSUE TITLE
Operation.Request ignores verify parameter

### ISSUE THREAD

**Issue by FedericoCozzi** [Dorthu/openapi3#47]
Hello,
I think Operation.Request ignores "verify" parameter.
It should be forwarded to self._session.send on line 297
result = self._session.send(self._request.prepare(), verify=verify)

**Comment by anchitarnav** [comment]
Created a Pull Request for fix of this issue: https://github.com/Dorthu/openapi3/pull/84

If a maintainer is coming across this, kindly review.
