### ISSUE TITLE
Capturing noncompliant replies

### ISSUE THREAD

**Issue by smurfix** [Dorthu/openapi3#80]
* I send off a request
* the server returns 403
* however this error is not mentioned in the server's spec (they rarely are)
* thus I get a `RuntimeError: Unexpected response 403 from listAutoReceptionists (expected one of 200, no default is defined`

This has two problems.

* it's a generic `RuntimeError` instead of an OpenAPI3-specific subclass (unexpected reply code, nonconforming body, …)
* the response object is not attached to the error. Thus I cannot easily react intelligently; e.g. my code might want to recreate the JWT auth token on a 403, retry on 408, slow down substantially on 429, alert the operator if/when the reply's body is nonconforming, etc..

Forcing the server operator to update their *censored* spec is not really an option here, also I actually like to get an exception at this point. Just not a generic one.

**Comment by Dorthu** [comment]
This makes sense.  I think defining a new exception class that encapsulates the unexpected response is a reasonable solution.  I'll address this by adding a `UnexpectedResponseError` that extends `RuntimeError` and includes a `response` object (the full response), and maybe a convince `status_code` attribute that captures the undeclared status code the server returned.

**Comment by Dorthu** [comment]
This was released in 1.6.5
