### ISSUE TITLE
Contact fields that should be optional are considered required, resulting in raised SpecError.

### ISSUE THREAD

**Issue by kirypto** [Dorthu/openapi3#82]
When parsing a JSON spec, if the `contact` object is specified but missing _any_ of `name`, `url`, or `email`, a `SpecError` is raised:
```
openapi3.errors.SpecError: Expected info.contact to be of type Contact, with required fields ['name', 'url', 'email']
```

As far as I can tell from research, all three of these fields are optional:
- [OpenAPI Specification v3.0.3](https://spec.openapis.org/oas/v3.0.3#contact-object) _(I linked v3.0.3, but it looks to be the same for other versions as well)_
- When visiting the online [Swagger Editor](https://editor.swagger.io/), assuming you don't have anything stored in your browser, the example spec generated only has `email: "apiteam@swagger.io"` in the `contact` object.

**Comment by kirypto** [comment]
I will note that I fairly new to open source contributions, so please let me know if there is anything more that should be provided.

**Comment by Dorthu** [comment]
Thanks for the report!  I opened #83 to resolve this issue.
