### ISSUE TITLE
[Bug] - Expects incorrect type on parameter default 

### ISSUE THREAD

**Issue by TTitcombe** [Dorthu/openapi3#91]
Trying to parse a spec containing a parameter component with a numeric default with incorrectly throw and states that a string default was expected.

Version: `1.7.0`

Minimal example spec:

```yaml
openapi: 3.0.0

info:
  title: Test api
  description: test
  version: 0.1.0

paths:
  /test:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: A good test

components:
  parameters:
    someComponent:
      name: someComponent
      in: query
      schema:
        type: number
        minimum: 0
        default: 0
``` 

To experience the error, load the specfile with yaml and try `OpenAPI(spec)`. It should throw.
If you replace `default: 0` with `default: '0'`, it will not throw.

The given spec is valid yaml

**Comment by Dorthu** [comment]
After some investigation, the issue is that the `number` type wasn't recognized when parsing default values; I've added that in #94, which should resolve this.  Thanks for reporting it :+1:
